# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bibi/Documentos/GitHub/AlienOSS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bibi/Documentos/GitHub/AlienOSS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bibi/Documentos/GitHub/AlienOSS/CMakeFiles /home/bibi/Documentos/GitHub/AlienOSS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bibi/Documentos/GitHub/AlienOSS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AlienOS

# Build rule for target.
AlienOS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AlienOS
.PHONY : AlienOS

# fast build rule for target.
AlienOS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/build
.PHONY : AlienOS/fast

cpu/cpu.o: cpu/cpu.c.o
.PHONY : cpu/cpu.o

# target to build an object file
cpu/cpu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/cpu/cpu.c.o
.PHONY : cpu/cpu.c.o

cpu/cpu.i: cpu/cpu.c.i
.PHONY : cpu/cpu.i

# target to preprocess a source file
cpu/cpu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/cpu/cpu.c.i
.PHONY : cpu/cpu.c.i

cpu/cpu.s: cpu/cpu.c.s
.PHONY : cpu/cpu.s

# target to generate assembly for a file
cpu/cpu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/cpu/cpu.c.s
.PHONY : cpu/cpu.c.s

list/list.o: list/list.c.o
.PHONY : list/list.o

# target to build an object file
list/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/list/list.c.o
.PHONY : list/list.c.o

list/list.i: list/list.c.i
.PHONY : list/list.i

# target to preprocess a source file
list/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/list/list.c.i
.PHONY : list/list.c.i

list/list.s: list/list.c.s
.PHONY : list/list.s

# target to generate assembly for a file
list/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/list/list.c.s
.PHONY : list/list.c.s

log/log.o: log/log.c.o
.PHONY : log/log.o

# target to build an object file
log/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/log/log.c.o
.PHONY : log/log.c.o

log/log.i: log/log.c.i
.PHONY : log/log.i

# target to preprocess a source file
log/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/log/log.c.i
.PHONY : log/log.c.i

log/log.s: log/log.c.s
.PHONY : log/log.s

# target to generate assembly for a file
log/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/log/log.c.s
.PHONY : log/log.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/main.c.s
.PHONY : main.c.s

memory/memory.o: memory/memory.c.o
.PHONY : memory/memory.o

# target to build an object file
memory/memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/memory/memory.c.o
.PHONY : memory/memory.c.o

memory/memory.i: memory/memory.c.i
.PHONY : memory/memory.i

# target to preprocess a source file
memory/memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/memory/memory.c.i
.PHONY : memory/memory.c.i

memory/memory.s: memory/memory.c.s
.PHONY : memory/memory.s

# target to generate assembly for a file
memory/memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/memory/memory.c.s
.PHONY : memory/memory.c.s

process/instruction.o: process/instruction.c.o
.PHONY : process/instruction.o

# target to build an object file
process/instruction.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/process/instruction.c.o
.PHONY : process/instruction.c.o

process/instruction.i: process/instruction.c.i
.PHONY : process/instruction.i

# target to preprocess a source file
process/instruction.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/process/instruction.c.i
.PHONY : process/instruction.c.i

process/instruction.s: process/instruction.c.s
.PHONY : process/instruction.s

# target to generate assembly for a file
process/instruction.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/process/instruction.c.s
.PHONY : process/instruction.c.s

process/process.o: process/process.c.o
.PHONY : process/process.o

# target to build an object file
process/process.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/process/process.c.o
.PHONY : process/process.c.o

process/process.i: process/process.c.i
.PHONY : process/process.i

# target to preprocess a source file
process/process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/process/process.c.i
.PHONY : process/process.c.i

process/process.s: process/process.c.s
.PHONY : process/process.s

# target to generate assembly for a file
process/process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/process/process.c.s
.PHONY : process/process.c.s

scheduler/scheduler.o: scheduler/scheduler.c.o
.PHONY : scheduler/scheduler.o

# target to build an object file
scheduler/scheduler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/scheduler/scheduler.c.o
.PHONY : scheduler/scheduler.c.o

scheduler/scheduler.i: scheduler/scheduler.c.i
.PHONY : scheduler/scheduler.i

# target to preprocess a source file
scheduler/scheduler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/scheduler/scheduler.c.i
.PHONY : scheduler/scheduler.c.i

scheduler/scheduler.s: scheduler/scheduler.c.s
.PHONY : scheduler/scheduler.s

# target to generate assembly for a file
scheduler/scheduler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/scheduler/scheduler.c.s
.PHONY : scheduler/scheduler.c.s

semaphore/semaphore.o: semaphore/semaphore.c.o
.PHONY : semaphore/semaphore.o

# target to build an object file
semaphore/semaphore.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/semaphore/semaphore.c.o
.PHONY : semaphore/semaphore.c.o

semaphore/semaphore.i: semaphore/semaphore.c.i
.PHONY : semaphore/semaphore.i

# target to preprocess a source file
semaphore/semaphore.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/semaphore/semaphore.c.i
.PHONY : semaphore/semaphore.c.i

semaphore/semaphore.s: semaphore/semaphore.c.s
.PHONY : semaphore/semaphore.s

# target to generate assembly for a file
semaphore/semaphore.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/semaphore/semaphore.c.s
.PHONY : semaphore/semaphore.c.s

ui/main-window.o: ui/main-window.c.o
.PHONY : ui/main-window.o

# target to build an object file
ui/main-window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/ui/main-window.c.o
.PHONY : ui/main-window.c.o

ui/main-window.i: ui/main-window.c.i
.PHONY : ui/main-window.i

# target to preprocess a source file
ui/main-window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/ui/main-window.c.i
.PHONY : ui/main-window.c.i

ui/main-window.s: ui/main-window.c.s
.PHONY : ui/main-window.s

# target to generate assembly for a file
ui/main-window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/ui/main-window.c.s
.PHONY : ui/main-window.c.s

ui/utils.o: ui/utils.c.o
.PHONY : ui/utils.o

# target to build an object file
ui/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/ui/utils.c.o
.PHONY : ui/utils.c.o

ui/utils.i: ui/utils.c.i
.PHONY : ui/utils.i

# target to preprocess a source file
ui/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/ui/utils.c.i
.PHONY : ui/utils.c.i

ui/utils.s: ui/utils.c.s
.PHONY : ui/utils.s

# target to generate assembly for a file
ui/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlienOS.dir/build.make CMakeFiles/AlienOS.dir/ui/utils.c.s
.PHONY : ui/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AlienOS"
	@echo "... cpu/cpu.o"
	@echo "... cpu/cpu.i"
	@echo "... cpu/cpu.s"
	@echo "... list/list.o"
	@echo "... list/list.i"
	@echo "... list/list.s"
	@echo "... log/log.o"
	@echo "... log/log.i"
	@echo "... log/log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memory/memory.o"
	@echo "... memory/memory.i"
	@echo "... memory/memory.s"
	@echo "... process/instruction.o"
	@echo "... process/instruction.i"
	@echo "... process/instruction.s"
	@echo "... process/process.o"
	@echo "... process/process.i"
	@echo "... process/process.s"
	@echo "... scheduler/scheduler.o"
	@echo "... scheduler/scheduler.i"
	@echo "... scheduler/scheduler.s"
	@echo "... semaphore/semaphore.o"
	@echo "... semaphore/semaphore.i"
	@echo "... semaphore/semaphore.s"
	@echo "... ui/main-window.o"
	@echo "... ui/main-window.i"
	@echo "... ui/main-window.s"
	@echo "... ui/utils.o"
	@echo "... ui/utils.i"
	@echo "... ui/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

